### ISSUE TITLE
Root slash is an error in LS and CD

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#1]
First of all, this is super cool!!

I noticed that if I type 

$ LS SBIN

...then it lists the SBIN directory. But if I type 

$ LS /SBIN

... then it does nothing. Same for the CD command. Is this how old Unix was where the "/" was insignificant?

**Comment by burniouf** [comment]
No, it is not an issue, as “LS /” lists all online ProDOS volumes.
The slight difference with Unix is that root=/ in Unix, and in A2osX, root=/BOOT_VOL.

**Comment by burniouf** [comment]
#336 : many corrections & new functionalities about LS,CD...(see description)

Could you give it a try?

**Comment by burniouf** [comment]
..and LS / now works!

**Comment by xandark** [comment]
Very nice! It now seems to perform how I'd intuitively think it should. 

Did the LS -L format change? If so, I like this version now.

Though I finally figured out what was throwing me off about the way directories are displayed from LS and how it was confusing me.

When I do a LS, I see 

/ETC
/BIN
/USR

...and so on. Because I see the "/" in front of the directory name, it made me instantly think that that folder is hanging off the root "/". But it was just a signifier that it's a directory, that's all. It was confusing me for days.

So I have a suggestion: Put the / after the directory name, like the way modern LS is implemented:

ETC/
BIN/
USR/

That way I and others won't think that ETC is at /ETC, but rather implied to be at /A2OS.BOOT/ETC.

**Comment by xandark** [comment]
Another suggestion that would've made it easier for me to understand "where I am" is to have a PWD command. That would've cleared up a lot of my confusion too.

**Comment by burniouf** [comment]
just type : 
$ CD
;-)
i'll add an alias for PWD.

**Comment by burniouf** [comment]
#338 : Added PWD and printing DIR/ as suggested.
Please check.

**Comment by burniouf** [comment]
Hello,

 

Thanx for your support!!!

 

No, it is not an issue, as “LS /” lists all online ProDOS volumes.

 

The slight difference with Unix is that root=/ in Unix, and in A2osX, root=/BOOT_VOL.

 

Btw, there is still bugs in the DIR API that sometimes make “/.” Appear twice. Working on it while implementing “LS –R”.

 

 

 

De : xandark [mailto:notifications@github.com] 
Envoyé : samedi 22 octobre 2016 09:37
À : burniouf/A2osX
Objet : [burniouf/A2osX] Root slash is an error in LS and CD (#1)

 

First of all, this is super cool!!

I noticed that if I type 

$ LS SBIN

...then it lists the SBIN directory. But if I type 

$ LS /SBIN

... then it does nothing. Same for the CD command. Is this how old Unix was where the "/" was insignificant?

**Comment by xandark** [comment]
Excellent, excellent, excellent! :) Works intuitively great now, just as I am expecting! This is so cool! 

I played around for awhile and I couldn't find anything regarding paths and directories that felt off. Made some subdirectories, CD'd into them, moved around, LS -L and it all is smooth.

**Comment by xandark** [comment]
> just type :
> $ CD
> ;-)
> i'll add an alias for PWD.

Much appreciated! 

As an aside, I did not think to try just typing CD because in modern implementations, typing CD causes the current working directory to switch to the user's home directory. I didn't think it would do the equivalent of a PWD.
