### ISSUE TITLE
echo with no arguments returns a "Syntax Error ($CF)"

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#10]
If I just want to have a blank line, I cannot currently do so.

I also tried:

$ ECHO -E "\n"
-E "\n"

**Comment by burniouf** [comment]
#382

**Comment by xandark** [comment]
I notice it now says "Syntax Error ($CF)" and I have to say that I enjoy seeing "Syntax Error" :)

**Comment by burniouf** [comment]
Echo \n is implemented since commit #382
see README.md

**Comment by xandark** [comment]
Okay, I see in the README.md it says of ECHO:

> \b,\e,\f,\n,\ and \% supported

Trying this:

/A2OSX.BOOT/$ ECHO foo
foo/A2OSX.BOOT/$

I'm used to seeing echo outputting a trailing CR at the end of an echo line. Is there a reason to not have a trailing CR by default?

Regarding the form-feed escape code, \f, if I type:

/A2OSX.BOOT/$ ECHO foo\fbar

I was expecting to get as the bash echo:

foo
     bar

but instead \f clears the screen. 

What does the \e code do?
What does the \% code do? 
These are new to me.

**Comment by xandark** [comment]
As for ECHO not outputting a trailing CR by default, that also aligns with the issue from #12

**Comment by burniouf** [comment]
/e = ESC, to print ANSI sequences....
/f = FF = clear screen
/% print .... "%"
see printf docuemntation

**Comment by burniouf** [comment]
try ECHO \e[7mfoo\e[0mbar\n
;-)

**Comment by burniouf** [comment]
well, seems that we are close to the BASH printf command.....quite easy to do, just need to add support for "quoted strings" in Kernel ARG API ...and "%08d" like experssions parsing is already implemented in CPrintF.
I suggest closing all enh issues related to SH scripting and open a GitHub subproject on this matter. Who knows, another developer could be affected to it !!!

**Comment by xandark** [comment]
> try ECHO \e[7mfoo\e[0mbar\n

Very nice :)

**Comment by xandark** [comment]
> well, seems that we are close to the BASH printf command.....

Have you seen this project...? Would that be useful here?

https://github.com/Michaelangel007/apple2_printm

**Comment by xandark** [comment]
> I suggest closing all enh issues related to SH scripting and open a GitHub subproject on this matter. Who knows, another developer could be affected to it !!!

Ah, because it's taking up too much of the focus away from the kernel part of this project? Yes, that makes sense to me.

**Comment by burniouf** [comment]
took a look at printm.
This printm project is typically "genius" piece of code.....completely isolated, and so, useless in the current state.
This illustrates perfectly why i want to gather this kind of thinking in an environment so it becomes usefull to everybody....same for a bunch of other projects, like for example marina IP stack from macgui.com : http://marina.a2hq.com .....and many others...

**Comment by xandark** [comment]
wouldn't hurt to reach out to them and ask them to see if they're interested in bringing it to this platform, as all authors want people to use their code, and you'd be making their code more usable

**Comment by burniouf** [comment]
fix for this issue : #399

**Comment by xandark** [comment]
Yup, good :)
