### ISSUE TITLE
TERM Program

### ISSUE THREAD

**Issue by patrickbst** [burniouf/A2osX#102]
Would it be possible to make a program that would be a VT100 client over the SSC.  This would be useful for testing the SSC/TTY on physical Apples.  I was thinking taking the Terminal part of TELNET and using the SSC driver instead of the NET driver for IO?

**Comment by patrickbst** [comment]
If we made this TERM program it would be useful for people with Apple //c who cannot have ethernet cards.  They could plug in a WiModem to "telnet"-like to internet BBS as well as to A2osX systems.  Or with a null modem cable, a //c could be a terminal for a //e or GS running A2osX.

**Comment by burniouf** [comment]
Implemented in #1711

**Comment by patrickbst** [comment]
Command Guide updated to include doc for TERM.  Closing.
