### ISSUE TITLE
CUT -f is not the same as CUT -F

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#107]
![Screenshot 2019-10-18 16:41:28](https://user-images.githubusercontent.com/5048913/67134266-349c7c00-f1c6-11e9-96bb-6bfd8ef8c483.jpeg)

While 

$ ls -l 

has the same output as 

$ls -L

the same is not true for CUT and its -F switch.

**Comment by xandark** [comment]
from RC 1643

**Comment by burniouf** [comment]
FIX in 1653

**Comment by patrickbst** [comment]
Tested and confirmed fixed.  Closing.
