### ISSUE TITLE
CAT is adding a CR between files where none exists

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#11]
CAT is adding a CR between FILE1 and FILE2, which is probably an artefact of forcing a trailing CR so that the shell's prompt starts on a new line. That CR insertion behaviour will have to be removed and the burden put onto the shell to check to see if it needs to add a CR when it prints its prompt.

I tested this assumption under Bash and found that all textual files have a terminating CR (actually LF). It's impossible for me to make a text file without one, like using Nano, or by doing a simple "echo 'blah' > /tmp/test". Using a hex-editor, I see that even that this "/tmp/test" file has a terminating CR.

Likewise with my Linux machine, if I use the hex editor to remove the CR, cat will still add a CR for me in interactive shell mode when there's only one argument to cat. With more than one argument, cat correctly concatenates the two files on screen with no intermediary CR, as I expect it would. SHELL's CAT doesn't do this, and puts a CR where one doesn't exist.

**Comment by burniouf** [comment]
#384

**Comment by burniouf** [comment]
Sorry, it means this bug #11 in fixed in commit #384.
