### ISSUE TITLE
DNSINFO Lockup

### ISSUE THREAD

**Issue by patrickbst** [burniouf/A2osX#110]
If you run DNSINFO without a network you get an appropriate error message (TCP/IP Not Loaded).  If you run it a second time (because why not) it locks the computer.

**Comment by patrickbst** [comment]
Added note.  On a clean boot, run the command, get the error, free memory drops by 7-8K.  The command should exit cleanly.

**Comment by burniouf** [comment]
FIX in #1674

**Comment by patrickbst** [comment]
Confirmed fixed, used 1690.  Booted STABLE/FULLBOOT, ran DNSINFO, gives proper no network error.  Loaded driver but not network, again gives appropriate error.  Loaded tcp and ran again, it worked.  then inserted HOST and tested that you could telnet to that entry.  All works as expected, no issues from the errors (clean exits).  Closing.
