### ISSUE TITLE
SH : Piped internal commands not closing output pipes properly

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#111]
![Screenshot 2019-10-30 15:51:21](https://user-images.githubusercontent.com/5048913/67904960-30108580-fb2d-11e9-9b05-d3160c671ce4.jpeg)

Build 1681 from STABLE.140.po

**Comment by patrickbst** [comment]
Confirmed, still exists in 1690.

**Comment by burniouf** [comment]
FIXED IN #1692

**Comment by patrickbst** [comment]
Tested in 1694.  Confirm fix for this particular use case "ECHO pipe to CUT" as well as an early case with DATE.  In addition, tested double piping and confirmed that PID=xx no longer issued on PIPEs.  New STABLE media posted with fix.  @xandark please confirm and close issue.  Thanks.

**Comment by xandark** [comment]
Tested in 1694 and works, very nice!
