### ISSUE TITLE
READ -S Delete issue

### ISSUE THREAD

**Issue by patrickbst** [burniouf/A2osX#115]
If you call the read command with the -S option, if the user presses the DELETE key, the cursor will move left and erase other text on the screen.

Side note, not sure if bug, but READ -N 0 Avar will not return the Escape Key (27), in fact if you press escape, you then have to press another key, before a 3rd key which gets registered by the READ command.

**Comment by patrickbst** [comment]
Tested in 1699, issue still exists (READ -S), hitting delete erases screen characters to the left.  Also please confirm if READ -N 0 should be able to capture Escape (27) or not.  Thanks.

**Comment by burniouf** [comment]
Fix in #1700

**Comment by patrickbst** [comment]
Tested with 1701, on AW and //e, confirmed fixed.  Closing.
