### ISSUE TITLE
EDIT doesn't follow Unix tradition of all files ending with a CR

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#12]
I noticed that EDIT allows me to make text files that do not have a terminating CR. 

I suggest following the Unix tradition and have all text files have a terminating CR, either from EDIT or from an "echo 'blah' > /tmp/test".

**Comment by burniouf** [comment]
but echo -n  'blah' > /tmp/test should be able to create a non CR-terminated file, right?

**Comment by xandark** [comment]
> but echo -n 'blah' > /tmp/test should be able to create a non CR-terminated file, right?

Yes, I just verified that's the case.

**Comment by burniouf** [comment]
i think i won't make EDIT adding a CR at end of file.
it may be a nice feature to create response file like : $ test.sh < response.txt
(well, i just met the case at work:-)

**Comment by xandark** [comment]
If EDIT just added one default character, a CR, when a new file is created, and had a rule that it wouldn't delete a CR if there's only one left, that would make all new files guaranteed to have a terminating CR. Just a thought.

**Comment by patrickbst** [comment]
Xandark, there are going to be use cases (we have some right now) were we want a piece of data stored in a file and we do not want a cr/lf/nl included in that data.  A good example is a file that contains a key that needs to be passed to a program and the hash of the key would change based on whether it includes a termination character or not.  In addition, while there are many aspects of A2osX that are "linux" like at its core, it is an Apple 2 program and it should produce Apple native files and those include ones with out terminating characters.
