### ISSUE TITLE
NSCUTIL date format

### ISSUE THREAD

**Issue by patrickbst** [burniouf/A2osX#123]
The NSCUTIL command should be updated to require date/time in the format YY/MM/DD,HH:MM:SS.  Currently YY and DD are reversed.

**Comment by patrickbst** [comment]
Additional UI suggestions.  Change the standard output of NSCUTIL (with no param) to only
DD/MM/YY,HH:MM:SS
which will match the set date/time format above.  Add a -H option that prints the "To Rest chip and set clock , type.....etc".  Add a -A (all) option that prints date/time and the Detected, OSC=1...etc.  Stuff that now appears at top of output (this should not print be default).  Have NSCUTIL exit with error (E0?) if no clock is present to set.  This would be useful for an install script that runs NSCUTIL and if gets error, does nothing, but if no error can ask user if they want KM.NSC installed (or install automatically).

The pared down output of this command would provide the "seconds" requested elsewhere and would eliminate need to add to SH/Prodos.  Also would reduce need of SH -E (???) option.

**Comment by burniouf** [comment]
should return MLI.E.NODEV		.EQ $28 if no clock present

**Comment by burniouf** [comment]
# 1789 : date format changed

**Comment by patrickbst** [comment]
Confirmed that date format has changed.  Also, NSCUTIL does report No device $28 on gs.  Closing issue.
