### ISSUE TITLE
A2OSX.KCONFIG should be renamed

### ISSUE THREAD

**Issue by patrickbst** [burniouf/A2osX#127]
I suggest that this file be named A2OSX.CONFIG, rather then KCONFIG.

**Comment by burniouf** [comment]
no because it exactly matches KCONFIG parameter block loaded at $BEF0->$BEFF BEFORE kernel is INITed

**Comment by patrickbst** [comment]
True, but could you not rename that block A2osX.CONFIG.  This would of course require changing A2osX.KCONFIG to A2osX.CONFIG everywhere, which is about 20 places in 5 or so files (most hits in KCONFIG.S itself, but a bunch elsewhere like Asosx.i, Kernel.s.init, etc.

**Comment by patrickbst** [comment]
i Kould try and see how badly i breaK everything! A Khristmas present.  lol
