### ISSUE TITLE
Project page needs more of an overview of project's goals

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#13]
I've been wanting to promote this project but even though think it has great potential, I don't know enough about the goals and capabilities of this kernel and shell to tell others exactly _what it is_.

Could you write something about that at the top of the project .md file so that people can get a sense of just what you're aiming for? Maybe it'll make it easier for people to decide if they're a fit for this or not.

I know I like it because I have a passion for the openness and power of Linux and seeing it on a II is fantastic. 

So what is it? :)

**Comment by burniouf** [comment]
well, maybe organize it  in subprojects could help understanding....but i don't master enough this Github feature....

**Comment by burniouf** [comment]
if you could provide some template and/or doc format, that could help....

**Comment by xandark** [comment]
Well, what I was thinking was that at the top of the README.md, it says "Multi-Tasking OS for Apple II". Can you just expand on that vision right after that line? I'd like to know more about what that means, especially because it seems so intriguing but nearly impossible. My first thought was, "really? preemptive multitasking? or just cooperative multitasking?"

**Comment by burniouf** [comment]
OK, as english is not my native language, feel free to add/correct .md files

**Comment by xandark** [comment]
Much better! And perfectly understandable too.

"Its principal goal is to collect all "genius" 65c02 pieces of code ever written here and there, concentrated in the same environment."

And very cool to hear about your vision! 

It made me think to see if the PLASMA language could be added, as that is the coolest new language for the Apple II these days.
