### ISSUE TITLE
WC does not accept piped input

### ISSUE THREAD

**Issue by patrickbst** [burniouf/A2osX#130]
The WC command appears to only be able to work with files **WC filespec** and not be used in a pipe chain . **CAT PROFILE | WC**.

**Comment by patrickbst** [comment]
Also, the options _M, -L. -W appear to have no effect. WC always prints out the same display of 3 numbers and a filename.  If an option is given (say -M) then WC should only return one number (no file name) especially when piped, that way one could do a **SET A = 'CAT PROFILE| WC -L' and have $A set to the number of lines in PROFILE.

**Comment by burniouf** [comment]
#1790 : now piping & all 3 switches wired

**Comment by patrickbst** [comment]
Tested in 1791.  WC now works as pipe target and all options work.  Note however if you do the example above **SET A =`CAT INIT|WC -L`** . those are backticks.  do this in etc.... then ECHO $A you get as result "Usage : CAT FIle1....."   however if you CAT INIT|WC -L at cmdline you get the result you expect.  Closing this issue as all WC issues address.  Will test more and open new issue for `` issue if needed.
