### ISSUE TITLE
Various commands give syntax errors with the -H flag

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#132]
Build 1784 on the floppy disk version

ECHO, CD, LS, and CAT give a [$78]:Syntax Error message. Only CAT succeeds partially.

![Screenshot 2019-12-07 20:14:46](https://user-images.githubusercontent.com/5048913/70384093-4381ee00-192e-11ea-9cad-a7be94da872e.jpeg)

**Comment by xandark** [comment]
I just checked the Command Guide and realized that those commands do not have a -H. Well CAT says it doesn't have a -H switch, but it actually does, so the documentation for it needs to be updated. And CAT itself needs a fix so it doesn't display a syntax error after displaying its help.

I'd argue that LS should have a -H switch as it's an often used command that people will want to inspect for its capabilities.

**Comment by patrickbst** [comment]
Internal commands (See shell dev guide) do not have help.  This would be commands like CD, MD, REN, PWD, ECHO, IF, etc.  External commands may or may not have help, but almost all will output their **usage** text (which is all -H (help) does anyway) if you type the command without any arguments (the Usage screens you see above).  The syntax errors you are getting are correct (-H is an invalid argument to internal commands for instance).

**Comment by xandark** [comment]
Okay I see. So should we close this?

**Comment by patrickbst** [comment]
Will update doc to match commands.  Closing as syntax correct.  We will try to add -H to all commands in next major release.
