### ISSUE TITLE
Date stamp for new files seems corrupted

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#16]
If I do "EDIT foo" to create an empty file called foo, and then do a "LS -L", I see two columns of date stamps. The second column is accurate. That must be the creation date? But the first date column shows:

11-???-00 33:70

Is that supposed to be the modification column? Is it a display bug or a data bug?

**Comment by burniouf** [comment]
seems that ProDOS 2.0.3 does NOT setup creation date when creating a file, only mod time...EDIT uses regular MLI call to create a prodos file...
Kernel should be modified to maintain both dates as a workaroung

**Comment by burniouf** [comment]
quick testing shows thesame behaviour with MD TOTO....MTIME set but not CTIME

**Comment by burniouf** [comment]
a regular CATALOG from BASIC.SYSTEM confirm this behavior at ProDOS Level
will label it as "enh"

**Comment by burniouf** [comment]
no, my mistake....some lines cut in MLICREATE API CALL....."bug"

**Comment by burniouf** [comment]
#391

**Comment by xandark** [comment]
Okay, good. Seems to be fixed. 

I noticed that the other files have corrupted creation date stamps. Lots of "00-???-00" that could be cleaned up. Should I file another issue for that?

**Comment by burniouf** [comment]
could be an "enh" to display <NO DATE> instead

**Comment by burniouf** [comment]
... display NODATE instead....

**Comment by burniouf** [comment]
#395 : added <NO-DATE> is ls -L when CTIME and/or MTIME is not set

**Comment by xandark** [comment]
Okay, looks good now! :)
