### ISSUE TITLE
What's the status of the development?

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#17]
There seems to be a lot of code work going on. What's happening under the hood?

**Comment by burniouf** [comment]
Kernel 0.9 is cooking....
major rewrite of several API
main target is implementing stuff like MKNOD, MKFIFO, MKDEV.....and so on, to definitively allow TCP finalization.
as a concequence, shell could now implement "|" (pipe), ">>" and ">".....
a lot of work.....and i'm still alone.

working on other projects, also. (ROM for SCSI cards, ATLK reverse ingeneering as i still lack doc)

**Comment by xandark** [comment]
Very cool! I was wondering how'd you implement that aspect, this is shaping up to be a fantastic mini-Unix. Can't wait to see it!

Do you hang out on comp.sys.apple2.programmers? Or the [Apple II Enthusiasts group](https://www.facebook.com/groups/5251478676/) on Facebook? I'm sure there would be a lot of interest for what you're doing and possibly some extra hands too.

**Comment by burniouf** [comment]
An atempt has already been done in : 
https://groups.google.com/forum/#!topic/comp.sys.apple2.programmer/th594fUNiQI

May we could resurrect it....

**Comment by xandark** [comment]
Version 0.9 seems to boot much faster than 0.8.

**Comment by burniouf** [comment]
for now, only kernel is partially working, so STARTUP script is very simple.
That s  why it boots faster.
Check status of all files, they are actually still flagged "0.8" version, you should be able to monitor progress as all of them will be migrated to "0.9"

**Comment by xandark** [comment]
Been checking progress from time to time, excellent work! I've also been sending people your way, and good to know you got the AppleTalk reference for the II.

**Comment by burniouf** [comment]
yes, snhirsch helped a lot providing this doc. 
I ended up with ATINIT dissasembly.
It allows me to write KM.APPLETALK.
Now i'm seeking for a "Workstation Card" to test t & write AT* Commands.

**Comment by xandark** [comment]
Looking very good! Seems to be more solid than the last time I checked in. I noticed MOUNTNFS which I hadn't seen before.

**Comment by burniouf** [comment]
well, i need feedback about all the core BINs & Commands that i upgraded these days.....
once debugged, i would like to switch back to TCP asap.
MOUNTNFS is here just to not forget it, for now....
as NFS is UDP based, this is not the priority, first i must close TCP to make the IP stack completed.

**Comment by xandark** [comment]
The IP stack looks much improved since last time, at least from the screen shots. I don't have an Uthernet card to test that with, and that crashes AppleWin running under Wine on Linux, but those screen shots looks very cool!!

The other thing that caught my eye was the DHGR driver. I'm really curious to hear what you have planned with that..?

**Comment by burniouf** [comment]
- Interesting, Uthernet emulation works fine on windows/Applewin....try contact Applewin team on github, maybe they could find a solution.

- DHGR.DRV / LIBGFX is first step to write Windowed GUI.....

**Comment by xandark** [comment]
I'm using the latest Applewin, but I'm using it under Wine emulation under Linux, so it's not running in a perfect Windows environment. I'd have to contact the Wine developers and file a ticket with them. (I'm not a Microsoft fan so I won't run their OS's directly.)

A windowed GUI? Nice. But do you think a 1MHz machine will make be fast enough? As a comparison, have you heard of Quark Catalyst Program Selector? It's the closest I've ever seen someone make a perfect clone of the early Mac desktop interface for a II. And it really looks beautiful on a monochrome monitor in 560x192 graphics! I've actually put it on a floppy disk and booted it up on my //c and played with it for awhile. It's truly fascinating to see because it's such a faithful port, but I ultimately concluded that it was just too slow to be useful. Very cool, but not useful day-to-day. 

Check it out and see for yourself, though I think it requires a mouse...
ftp://ftp.apple.asimov.net/pub/apple_II/images/disk_utils/quark_catalyst/

It led me to think of what kind of interface would be most suited to the II in a _practical_ way, and I've thought that a non-overlapping tiling-like window manager, like those used in Linux, or an overlapping card interface, as utilized by AppleWorks would be something that I'd use on a II.

But still, your work is very cool!

**Comment by burniouf** [comment]
just tried catalyst, interesting work!!!
i'm working on graphic primitives, if i manage to get acceptable speed on BitBlt function, i will go ahead.
DHGR.DRV is massively table driven to speed up things (specially this nasty DIV by 7 stuff!!!)
LIBGFX should also be highly optimized....
but again, still alone on this project, if someone at least could promote it.. ;-)
this will helps finding additional developers....i concentrate few time i have on coding, don't even have time to chat on comp.sys.apple.....

**Comment by xandark** [comment]
Well, regarding promotion, have you joined the "[Apple II Enthusiasts](https://www.facebook.com/groups/5251478676/)" group on Facebook? It's very popular and getting in there and posting updates about A2osX will get you some easy publicity. Plus, with so many people going to KansasFest soon, I think people should know about this project because people hack on software at KansasFest for a week.

**Comment by xandark** [comment]
How much space is taken up by the tables for the bit shifting?

**Comment by xandark** [comment]
Now that I think of it, space considerations shouldn't be an issue because most people who are around these days have added more memory to their II on top of the 128K. So if your memory management is good, then having large shift tables are okay.

**Comment by xandark** [comment]
Just posted that you're looking for help on the [Facebook "Apple II Enthusiasts" group](https://www.facebook.com/groups/5251478676/). I haven't been able to test as I would've liked to due to real life issue, but I'll be back!

**Comment by burniouf** [comment]
Thanx a lot for promoting A2osX!!!
hope all is ok now at your side.
I'm back from the seas....will soon resume coding.

**Comment by xandark** [comment]
You're welcome, and there was a positive response to it :) 

I have just moved to my new home after being rootless for 5 months and drifting around. So I hope to be able to test some more when my life stabilizes.

This is still a very cool project and others need to be aware of it. Have you joined Facebook and that group? Because that group seems to be the most active, central place of all Apple enthusiasts around the world.

**Comment by burniouf** [comment]
Another good news for you : you have just been promoted "A2osX Official Communication Director" ...

... Congratulations !!!!

;-)

**Comment by xandark** [comment]
Um, okay! :)

I posted about A2osX here: https://www.facebook.com/groups/5251478676/permalink/10156624963063677/  There are many comments and two people shared the post.

BTW, are you on Facebook? Or are you opposed to Facebook for ideological reasons?

**Comment by burniouf** [comment]
I'm not particularly opposed to FB, i just ... don't care about it....
BTW, seems i've just been accepted in this community!!
will try to post something once this badly wounded shoulder got fixed, preventing me to type with 2 hands...
(took me 10 minutes to write this message  :-( )

**Comment by xandark** [comment]
Ouch, hope it heals rapidly, though I think that should be your priority, not Apple II coding. 

Yes, do check out the Apple II Enthusiasts group, you can do that by just scrolling and seeing how close everyone is and how helpful, and, well, enthusiastic :) They would love to be able to hear updates and question you directly. I posted there, but I cannot answer many questions.

**Comment by burniouf** [comment]
Done! My first posts into FB.....!!!! i'm back in the 21th century's technology.... ;-)

**Comment by xandark** [comment]
Haha, right on! :)

**Comment by patrickbst** [comment]
Xandard have you tried using any of the latest builds? Most importantly 0.92? There have been a lot of changes/enhancements to A2osX in the last couple of months, including significant enhancements to scripting, a TELNETD server, rewritten Kernal, INIT system, DHCPCLNT etc.   We would love your feedback on the current release.  We have created a SLACK group for testers and can send you an invite to that feedback channel as well if you like.
