### ISSUE TITLE
Corruption on boot up

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#19]
Seems that much has progressed since I picked up A2osX last with version .9 of the kernel. I notice that the boot up screen has textual corruption, though I'm sure you're well aware of that. And also in the login screen too, though that's likely a separate issue?

**Comment by burniouf** [comment]
Boot up:
Could you be more precise about boot up screen corruption ? which load stage ?  etc.....
Login:
About the square on top of "login:" : this is caused by TELNET special code not handled properly by CONSOLE.DRV. must open a separate ticket fo that.

**Comment by burniouf** [comment]
#579 : CONSOLE.DRV, Fixed TELNET chars printed on top of login:

**Comment by xandark** [comment]
![a2osx-corruption-bug gif](https://user-images.githubusercontent.com/5048913/27153668-359dc7ba-5107-11e7-806a-7d92e9f8d663.gif)

I've added a gif animation to show you what I see in the boot up corruption issue, so you can see the exact point it throws garbage on my screen. This should help.

**Comment by xandark** [comment]
And I've confirmed that the login corruption is fixed.

**Comment by burniouf** [comment]
hmmmmm....seems this is the VSDRIVE that mess up the screen...
i just checked, Applewin on Windows does NOT trash the screen....
try deleting the KM.VSDRIVE File....

**Comment by burniouf** [comment]
or KM.RAMWOKS.....while formatting......

**Comment by xandark** [comment]
Okay, deleting KM.VSDRIVE solved the first, long paused screen corruption, yet a shorter-paused corruption remained. So I deleted KM.RAMWORKS and that fixed the second corruption on boot.

So with those files deleted, there is no corruption on my boot, and it's faster too.

**Comment by burniouf** [comment]
mmmm.....seems AppleWin has a known bug related to RW emulation....the hardware is designed to  forces BANK 0 of RAM used while video refresh, whereas Applewin uses the currently selected BANK, which may have been left selected by last /RAM3 access.....i checked on real hardware....no screen flicker seen....

**Comment by xandark** [comment]
Testing on MAME 0.185 with a RamWork3, the corruption doesn't exist:

$ mame apple2ee -sl5 thclock -aux rw3 -sl2 softcard -floppydisk1 A2OSX.BOOT\ \(1\).po

So yes, it's a AppleWin thing.
