### ISSUE TITLE
Short form of LS confusingly adds file type to be an extension of the file name

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#2]
There is a small detail that has been confusing me because it collides with my experiences from Unix.

In A2osX, when I do a LS, but not a LS -L, I see files displayed like this:

PRODOS.SYS  A2OSX.STARTUP.TXT  A2OSX.SYSTEM.SYS

where the ProDOS file type is appended to the file name. This confused me because I tried to do 

EDIT A2OSX.STARTUP.TXT

and nothing would appear. Same for

EDIT ETC/HOSTNAME.TXT

...even though EDIT properly displayed the filename in its status bar. I now realize that it was a confusion caused by LS tacking the extension onto the file name, as if it were actually a part of the name.

It would be more clear and more intuitive if the short version of LS omitted adding the extension onto the filename. That way I'd simply see:

PRODOS   A2OSX.STARTUP   A2OSX.SYSTEM

This is more clear and direct to my eyes. I wouldn't need to do any kind of mental processing of the file names.

I believe it's okay to omit the extension from the file names here because doing LS -L shows everything in detail.

**Comment by xandark** [comment]
I wanted to immediately see the contents of ETC/HOSTNAME.TXT. Not having a CAT command, I tried...

EDIT ETC/HOSTNAME.TXT

but that didn't display the file, nor did 

CD ETC
EDIT HOSTNAME.TXT

I later discovered that EDIT can only edit files without the .TXT extension, even if the short form of LS shows the file name including the extension.

Having the short form of LS omit the extension would be clearer here too.

**Comment by burniouf** [comment]
TYPE ETC/HOSTNAME does the job ;-)

please provide requirement for a reasonable CAT implementation (switches....etc....)

**Comment by burniouf** [comment]
#341, removed .EXT in LS, added L CMD in BIN/ as an alias for LS -L, Added -R switch for recursive DIR listing

**Comment by xandark** [comment]
Okay, LS is much clearer now without the extensions added on, and the new recursive switch is great. Bonus that Ctrl-S works as I was expecting :)

Having an alias is welcome as I was typing LS -L a lot. 

As a FYI, in the Debian/Ubuntu realm, in their .bashrc login file, they add a "LL" alias to indicate "ls -alF" (which is a long listing) and an "L" alias to indicate "ls -CF" (which is a variant on a short listing). Using L creates a bit more work for my brain because I'm expecting another format.

**Comment by burniouf** [comment]
L is coming from a past life, working a lot with SuSE SLES distribs.
The L, LL, or whatever are scripts calling LS with various switches....easy to add in BIN/...make your own ;-)

If -R , CTRL-S (and CTRL-C!) is working properly in LS, i will derive MV,CP,RM commands from this code.

**Comment by xandark** [comment]
Oh interesting that SuSE and SLES use L differently. 

I just looked at BIN/L and it's a simple text file, very easy to understand. I just made a LL variant easily enough.

I noticed that L contains this:

LS -L $2 $3 $4 $4

is there a reason to have duplicate $4's?

**Comment by xandark** [comment]
Yes, Ctrl-S and -C are working properly in LS -R, just tested them again :) 

This issues is now closed.

**Comment by burniouf** [comment]
no, it's a typo
should be : LS -L $2 $3 $4 $5 $6 $7 $8 $9
will correct this in next media
