### ISSUE TITLE
Hostname is absent from /etc

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#20]
Booting up and doing a LS ETC, I see that there are no files present. Is this intentional?

**Comment by burniouf** [comment]
Yes it is, add your own! ;-)
if this file is not present, TCPIP will generate a ramdom host name...

**Comment by xandark** [comment]
Okay, good to know and that could be mentioned somewhere in the documentation, as this is gearing up to be quite a powerful platform and others need to know how it all works and the philosophy behind it.
