### ISSUE TITLE
Deleting files won't work with provided lowercase file names

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#21]
$ cd sys
$ ls
$ rm km.vsdrive
$ ls
<KM.VSDRIVE still exists>
$ rm KM.VSDRIVE
$ ls
<KM.VSDRIVE is gone>

**Comment by burniouf** [comment]
file name are supposed to be case SENSITIVE, so rm km.vsdrive should NOT delete KM.VSDRIVE, but a least returns something like FILE NOT FOUND....

**Comment by xandark** [comment]
When I type "rm km.vsdrive", there is no "File not found" message. Just silence, which makes me think that it succeeded, but it did not.

In my mind, I know that ProDOS is not case sensitive, so I was not expecting case sensitivity.

Also if I create a file:

$ edit foo
(add some text, save it, exit)

... the file name appears in the directory as FOO, not foo, which is what I specified. Furthermore, if I type once more

$ edit Foo

... I still am editing FOO. It doesn't complain that "Foo" cannot be found.

So the case sensitivity is inconsistent, which is confusing for me. I'd love it if the commands preserved the case of file names when I create them, and show them in the same case in the directory listings, that would be nice. Seeing everything in CAPS is jarring on my eyes.

**Comment by burniouf** [comment]
added a result line in CP/RM/MV commands.

this is not a real bug, the behavior is as follow:
"RM foo" command tries to find any matching file with the pattern "foo", like it will have done with "RM Test*" or "RM TE?T"

if foo is not present, but FOO is, 'FOO' does not match 'foo' so no file deleted.

now, RM prints : "count file(s) deleted."

**Comment by xandark** [comment]
I see the "count file(s) deleted" and that at least tells me that it failed to delete the file I specified.

But this brings up a few comments in my mind. 

The first is that this "count file(s) deleted" feedback string violates the Unix philosophy that a command shouldn't give feedback if it completes successfully. In other words, silence is a sign of success.

The second thought is that I know that I'm on a ProDOS file system and it is a case-insensitive environment. I don't see why the system would think that I shouldn't be able to delete a file named FOO when I specify foo. 

I don't see that "foo" is a _pattern_, as you described the matching process. I see it as a literal.

Furthermore, I see that I can invoke RM as RM or rm or even rM. So there's some double-standards here. If this was a strict case-sensitive environment, and everything was treated the same way, then maybe I could get behind this, but as it is now, I'm confused as to what is what.

If case-sensitivity is enforced for ProDOS, I'd like to see it everywhere, and I'd prefer that all commands are lowercase, as in Unix.

**Comment by xandark** [comment]
On a side note: I am using the CP command and since ProDOS and the 1MHz Apple II is so slow, I am now appreciating having the visual feedback of its progress when it prints out "CP File:/a2osx.boot/ETC to /ram3/ETC...[OK]". So in this case, having visual feedback is welcome. Maybe the command could have a switch to make the command quiet, like -Q.

**Comment by burniouf** [comment]
see #588

**Comment by xandark** [comment]
I notice some inconsistencies with case-sensitivity...

$ cat bin/l                             # huh? this shouldn't work but it does
LS -L $2 $3 $4 $5 $6 $7 $8 $9
$ cp bin/l /ram3/bin/             # whereas with cp, it doesn't recognize "l"
0 File(s) Copied.
$ cp bin/L /ram3/bin/           # here, cp recognizes "L"
CP File:/A2OSX.BOOT/bin/L to /ram3/bin/L...[OK]
1 File(s) Copied.

So cat appears to be case insensitive while cp is case-sensitive.

**Comment by burniouf** [comment]
2 subjects in one:

- Command line Options, should have been ALL corrected now...

- Files & Dirs : i dig into ProDOS and the conclusion is that i will leave the case sensivity check to the underlying filesystem, (ProDOS, nfs....etc...)
I will leave the display of files with extra case information in version/min_version (see 'ProDOS' file in A2osX.BUILD) but i won't allow creation of lowercased files/Dirs in ProDOS FS...it will cause much trouble than bring functionality!!!!)

so the direction is:

- remove all uppercase conversion in commands
- make listdir API case unsensitive (for ProDOS FS)
- allow SHELL to understand UC & lc internal keywords.

Somethng else ?

**Comment by xandark** [comment]
- command line options: I notice that the lowercase  seem to be working, from a quick check.
- files & dirs: I understand about creation of lowercase file/dirs, though I still do like the long-term idea of getting on contact with John Brooks who could add such functionality to the new ProDOS 2.4 series

> I will leave the display of files with extra case information in version/min_version (see 'ProDOS' file in A2osX.BUILD)

I couldn't find what you meant by that. Help me see what you meant there.

> - remove all uppercase conversion in commands
> - make listdir API case unsensitive (for ProDOS FS)
> - allow SHELL to understand UC & lc internal keywords.

And everything you mentioned sounds good to me because it has the least amount of surprise and the most amount of congruence.

I'll wait until I'm the shell understands **$ rm bin/format** before closing this bug.

**Comment by burniouf** [comment]
in the A2osX.BUILD media, the 'PRODOS' file is tagged in 'version/min_version' to appear like 'ProDOS' (with 2 lowercase letters)

**Comment by xandark** [comment]
Okay, I was finally able to confirm this. Neither MAME nor AppleWin allow me to add an 800K disk to them, so I used GSport to boot A2osX.BUILD.po, and then figure out that I needed to type "-a2osx.system" to boot into A2osX :) Yes, I see the lowercase there, very nice.

**Comment by burniouf** [comment]
I use AppleWin (on Windows 7) and i mount A2osx.BUILD as S7D1 & A2osx.SRC as S7D2....this allow me to ASM all sources, then i type -RUN to exec A2osx.SYSTEM once ASMbled....and at $, i type MAKEBOOT to build the A2osX.BOOT media...
i'm surprised in does not work at your side.

**Comment by xandark** [comment]
Ahh, that's the trick. I never tried to attach it as S7D1.

**Comment by patrickbst** [comment]
Xandark, all of the lower case issues have been resolved since build 1047 (for reference we currently on 1124).  There is a spreadsheet in the main folder of this project that we use to internally track issues and all lowercase(LC) issues were merged into 115 and tracked/tested until finally resolved in 1047.  We would love for you to download the latest build and test and provide us any new feedback.
