### ISSUE TITLE
Renaming a file via the mv command doesn't work

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#22]
$ CD SYS
$ LS
$ MV KM.VSDRIVE KMVSD
MV File: /A2OSX.BOOT/SYS/KM.VSDRIVE to /A2OSX.BOOT/SYS/KMSDV/KM.VSDRIVE
Err: path Not Found [44]

(appears to treat the second argument to MV as a directory, not a target file name)

**Comment by burniouf** [comment]
commit #583 attempts to fix this bug.....but raising more bugs!!!!
i fear X.CPMVRM.S should be separated back t 3 distinct files....

**Comment by xandark** [comment]
Hm. Yes, just noticed that it's still there.

**Comment by burniouf** [comment]
Partially fixed....just an extra confirmation to remove....but as the code is shared between CP,MV,RM.....need complete testing...

**Comment by xandark** [comment]
Seems to partially work, as you just mentioned...

$ CD /RAM3
$ EDIT FOO
**<TYPE SOMETHING AND SAVE IT, THEN QUIT>**
$ MD BAR
$ MV FOO BAR/
[OK]
2 File(s) Moved.
**<a bug: why does it say 2 files were moved?>**
$ CD BAR
$ MV FOO ../.
MV File:/RAM3/BAR/FOO to /RAM3/BAR/../....
Err:Invalid Path [40]
**<note: doesn't seem to recognize the ../. notation>**
$ MV FOO /RAM3
MV File:/RAM3/BAR/FOO to /RAM3/FOO....[OK]
1 File(s) Moved.
$ LS 
./ ../ FOO
$ LS ..
../
**<note: the file FOO was *not* moved to the parent directory>**

**Comment by burniouf** [comment]
fixed in #601
A complete check of MV,RM,CP...and even LS will  be welcome! ;-)
