### ISSUE TITLE
README thoughts

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#23]
"Question : Pascal or C Compiler?"

I've programmed in both, and I much prefer C. 

Have you heard of [TinyC](https://en.wikipedia.org/wiki/Tiny_C_Compiler)? Or I wonder if it's possible to self-host [cc65](https://github.com/cc65/cc65)?

The other thought I had reading the README is that as a developer, I'd like to know what kind of benefits I would get from the A2osX platform, like does it make memory management transparent across all bank-switched memory? What limits does it impose on me as a programmer? What does it give me that would delight me?

Also, I think I remember having read that the inspiration for A2osX was that the first UNIX systems were 128K machines and UNIX was written in assembly. That got me excited, because I always thought the power of UNIX meant it had to be in a "big" machine architecture. I think this should be mentioned in the README, it's a great idea that's sticky to the mind.

**Comment by burniouf** [comment]
I started writing a C compiler, just to know about where it will drive me....for now, il did not met particular difficulties, and it helps me cleanup/reorganize the API a more "ANSI C" compliant way.
But the priority (between many others ;-) wil be completing the ASM....i leave it behind for a while, source is not Kernel 0.9 compliant!!!! as far as i remember, only MACROs where left to be written.
The idea is that CC will output assembly source code, that will be handled next by ASM.

**Comment by xandark** [comment]
Oh, okay, though I can see macros being very important in an assembler. 

> The idea is that CC will output assembly source code, that will be handled next by ASM.

Okay, and have you considered taking something like TinyC, which already has all the parsing and compliance done, and then modifying the code generator to produce ASM?

**Comment by patrickbst** [comment]
README has been updated with better executive summary description of A2osX.  In addition a new A2osX User Guide and an A2osX Developer Guide have been written (and our constantly being updated) with information on the design, features and benifits of A2osX.  Closing this issue.
