### ISSUE TITLE
Can files retain case sensitivity like in GS/OS?

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#24]
Can A2osX retain and display file and directory names with their originating case, like GS/OS does?

**Comment by burniouf** [comment]
A bit more complex:
ProDOS (the underlying FS) is NOT case sensitive, so the actual code is not bothering too much about that.

.....but.....

As foreign FS support is planned which may be case sensitive, a complete review of this behavior should be done.
Actually, Kernel 0.9 is designed to support "path filtering" that will be used to implement NFS mount....
and NFS should be able to access *NIX FS that may be case sensitive....
so, next step, NFS....

**Comment by xandark** [comment]
Okay got it.

However, I was unclear and referring to how I think I remember that GS/OS adds the ability of ProDOS file name to be lower case. I believe it had an addition of two bytes of bit flags, one bit for each character. Is that true? And if so, could A2osX support that natively?

**Comment by burniouf** [comment]
Apple Tech Notes: GSOS 2523008 Lowercase Filenames :

According to this TN, should be possible....as A2osX exposes a full File/dir API on top of native MLI calls, it may be possible to setup some sort of "filename translator" to convert from 15Ul to 15U+1/15bits and pass it to MLI....and vice-versa....
must check impact first on directories, and file search, wildcard filtering....

**Comment by xandark** [comment]
That would be very nice, and would make it more sense to enforce case-sensitivity on ProDOS.

**Comment by burniouf** [comment]
After further inverstigations, it should be easily possible to setup filenames with Upper and Lower case....
but:
- ProDOS wont allow "FILE" and "file" in the same directory.
- I did not find confirmation that the 2 bytes bitmap for lowercase is applicable for directory names
- if you type CD DIR1/Dir2, and real file system is DIR1/DIR2, but shown as Dir1/DIR2: ProDOS will accept this syntax, but A2osX should NOT, right?


so, technically, it is not so difficult, but the behavior to implement is not so simple.

**Comment by xandark** [comment]
> ProDOS wont allow "FILE" and "file" in the same directory.

That's acceptable considering the limitation of ProDOS.

> I did not find confirmation that the 2 bytes bitmap for lowercase is applicable for directory names

I confirmed that ProDOS retains lowercase for directory names. I did this by booting up GSport, creating a directory called "Foo" on a ProDOS disk, then launching BASIC.System into ProDOS 8 land. It shows as "FOO" there, but it shows as "Foo" from the GS desktop.

> if you type CD DIR1/Dir2, and real file system is DIR1/DIR2, but shown as Dir1/DIR2: ProDOS will accept this syntax, but A2osX should NOT, right?

Maybe it should depend on the filesystem that the user is on? If it's NFS, then it's strictly case-sensitive. But if it's ProDOS, then it's _case-insensitive yet case-preserving_. That's the only way I can think to make this work.

I see that the implementation will require more work, though this would make it shine.

**Comment by burniouf** [comment]
Ok, after digging into the kernel, an easy way was found to READ those 18 bytes mixed case filenames...
But i have to make room in AUX LC to host this extra code.....and finally broke everything! ;-)

btw, there is no way to CREATE,SET_FILE_INFO these files...no MLI call seems to handle these version/min_version bytes.

the only way is to write directly to ProDOS directory linked lists....

**Comment by xandark** [comment]
Gah! Make it fit! :)

Regarding CREATE,SET_FILE_INFO... since John Brooks now has a buildable, modifyable version of ProDOS that can even run on clones, it shouldn't be a stretch of the imagination to reach out to him and see if he could add support for this extended functionality. The ability for lower-case filenames is there, it's about time that it's taken advantage of.

[http://www.callapple.org/vintage-apple-computers/apple-ii/announcing-prodos-2-4-1-for-all-apple-ii-and-compatible-computers/](http://www.callapple.org/vintage-apple-computers/apple-ii/announcing-prodos-2-4-1-for-all-apple-ii-and-compatible-computers/)

**Comment by burniouf** [comment]
Ok, kernel now able to DISPLAY 18 bytes lowercase filenames (to check)

**Comment by xandark** [comment]
I'm having a difficult time verifying this. I want to type "touch foo" to get an empty file called "foo", but that command doesn't exist. I want to do "echo hello > foo" but that doesn't work yet. So the only way I can create a file is to do "edit foo". EDIT realizes that I specified "foo" and not "FOO", but it saves it as "FOO", which I don't want.

**Comment by xandark** [comment]
Check out this commentary for how MouseDesk is using ProDOS 2.5 to have mixed-case:

https://github.com/inexorabletash/a2d/issues/64

**Comment by patrickbst** [comment]
Moving this to 0.94 as a consideration for a future feature.

**Comment by burniouf** [comment]
Booting with ProDOS 203 will allow you to see mixed/lowercased dir/filenames. Pattern matching (ex: LS Fil*) will be case INsensitive.

Booting with ProDOS.FX allows you so see/create/manage mixed/lowercased vol/dir/filenames.
Pattern matching will be case sensitive.

ProDOS.FX allows you:
-  to boot from a mixed/lowercased Volume. 203 wont.
- use extended dir/filename syntax (like .profile or _UnderScored) ...203 wont be able to display it.
- Create TESTFILE and testfile in the same dir....203 will be disturbed !

....many more....

Soon, 203 & FX media available, closing.

**Comment by xandark** [comment]
I see that this issue is now closed, but I have a reservation about having multiple different ProDOS "kernels", each with their own incompatible behaviour. Especially regarding a kernel that will make it possible to have two different files in the same directory that differ only by case. 

I feel that this difference will fracture the compatibility landscape and prevent ProDOS 2.4.2+ from working with ProDOS.FX volumes. Unless we do a poll to know for sure, I feel it could lower A2osX's adoption.

I'm all for ProDOS to be a case INsensitive filesystem. I'm also for collaboration between John Brooks' effort and A2osX's.

**Comment by xandark** [comment]
Correction: ProDOS 2.5 not 2.4.2
