### ISSUE TITLE
EDIT's status bar flashes on every key press

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#25]
There seems to be a new change where typing anything in edit causes the status bar to flash as it updates. Is it possible to simply overwrite the status with the new info and not erase it between updates?

**Comment by burniouf** [comment]
Is this happens in AppleWin on your MAC ?
Real Hardware ?
I cannot reproduce this issue, same as RamWorks screen corruption?

**Comment by xandark** [comment]
This happens on both AppleWin and MAME .186 with the most recent floppy image uploaded 9 hours ago.

No, it's not the same as the RamWorks screen corruption issue, which MAME didn't exhibit. I don't have real hardware to test it with at the moment.

It appears as if the status bar is blanked to all white characters and then the text is redrawn.

**Comment by burniouf** [comment]
Ok, i see.....
this is a consequence in adding TELNET compliance to EDIT....
Will try to make it better...

**Comment by burniouf** [comment]
fixed in commit #587

**Comment by xandark** [comment]
Yes, much better now! :)
