### ISSUE TITLE
Upgrade ProDOS from 2.0.3 to 2.4.1

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#26]
With the excellent work updating ProDOS by John Brooks, should A2osX take advantage of those new fixes and use 2.4.1?

I believe all that is necessary is to copy the PRODOS file from the 2.4.1 disk to A2osX's boot disk.

[http://www.callapple.org/vintage-apple-computers/apple-ii/announcing-prodos-2-4-1-for-all-apple-ii-and-compatible-computers/](http://www.callapple.org/vintage-apple-computers/apple-ii/announcing-prodos-2-4-1-for-all-apple-ii-and-compatible-computers/)

**Comment by xandark** [comment]
From the recent KansasFest, there is a very interesting video of John Brooks talking about the new additions he made to ProDOS 2.4.1 and the new features he's working on for 2.5. Do check it out and reach out to John Brooks on comp.sys.apple2.programmers so that you can work together--you're pushing ProDOS more than others are so he should know about this project.

https://www.youtube.com/watch?v=Sm4D1wtWPck

**Comment by patrickbst** [comment]
The Version of ProDOS on BUILD (and I assume BOOT) is V2.0.3.  The most current version is 2.4.2.  We should update the version of ProDOS on our discs to match (largley to keep up with the date/clock corrections) and bug fixes.
--From S0019

**Comment by patrickbst** [comment]
The various versions of ProDOS have been added to A2OSX.MAKE image so that when official release media is made we can make sure to use the latest versions of ProDOS (and also make versions with older versions if needed for some reason).

**Comment by patrickbst** [comment]
For 0.93, the current project milestone, we have decided to include on the A2osX media a very slightly modified version of 2.0.3 which you will notice during boot fo ProDOS is labeled as 2.0.3tc.  This stands for ThunderClock and basically this version is an exact copy of 2.0.3 with 7 bytes changed to update the ProDOS year table to be current (it is the same work to correct the year that is done in 2.4.2/2.5 by John Brooks).  Note, we do test A2osX regularly with other versions of ProDOS (the author of this note regularly runs 2.4.2).  For consistency and support we will standardize on 2.03tc for this release and readdress which version of ProDOS should be included when we start creating 0.94 builds.

Also note, users can replace ProDOS with another version, or as is expected for many with hard drives/emulators, they can install A2osX onto a subdirectory of their HD/Drive which boots their preferred version of ProDOS.  In fact, we are planning for an upcoming release an "INSTALL" method that will create this subdirectory, copy the necessary files and make any changes to A2osX config files needed so people can run A2osX in this manner.

Closing this issue as it Answers the question/request posed.

**Comment by xandark** [comment]
Thank you for the illumination, @patrickbst 

Because others will be asking the same question, I suggest copying what you wrote and putting it in the NEWS section at the very least and also somewhere else that explains the rationales for what you're doing. After all, ProDOS is the heart of this new system and it has to make sense to people what we're doing.

I see that there is a new ProDOS.FX too. This also needs to be explained and why it's used instead of ProDOS 2.4.2.
