### ISSUE TITLE
Make switch option names case insensitive

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#27]
I discovered this when I typed out:

$ cp -r * /ram3

and got a usage message from CP, saying it didn't understand what I was doing. I didn't figure out that it needs a -R instead of -r. 

If the commands can be case-insensitive, letting me type in lower case, it seems reasonable to allow the user to type switch symbols in lower case too.

**Comment by burniouf** [comment]
see commit #588

**Comment by xandark** [comment]
Okay, great, I tried it again and the lowercase -r switch works now.
