### ISSUE TITLE
The shell would benefit from having a CAT command

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#3]
Upon playing around, I wanted to do one thing that I felt would've made my experience more rich, and I feel that the omissions are minor, yet they'd go a long way.

One is having CAT to print files to stdout. Yes, I know CAT is really for concatenating multiple files, but this is a quick way for me to see the contents of a file without putting me into any special mode. 

For example, I wanted to immediately see the contents of ETC/HOSTNAME, and a quick way would've been: 

CAT ETC/HOSTNAME

As a fallback, I then tried...

EDIT ETC/HOSTNAME.TXT

but that didn't display the file (due to the extension confusion issue mentioned in #2 ).

So in addition to having a CAT command, having a TOUCH command to create an empty file would round out the basic toolbox of commands to have in a shell. To be honest, I could live without TOUCH, but I couldn't live without CAT.

**Comment by burniouf** [comment]
TYPE ETC/HOSTNAME does the job ;-)

please provide requirement for a reasonable CAT implementation (switches....etc....)

**Comment by xandark** [comment]
Ah, yes, yes it does! I just figured out why TYPE wasn't appearing to work for me, because I was issuing

TYPE ETC/HOSTNAME**.TXT**

...which is what LS was showing me. And I would get a [46] code, not knowing what it meant. 

So CAT isn't so important this instant, but I'll think about switches and so on.

**Comment by burniouf** [comment]
i suggest:
CAT -B -N -S  FILE1 FILE2 FILE3.....
as a starting implementation.....enough?

**Comment by xandark** [comment]
Yes, those flags seem to be sufficient. The others seem to be rather obscure.

**Comment by burniouf** [comment]
CAT -A -N -S FILE1 FILE2 FILE3 is ready to be tested
-A = print all, 
-B is mandatory?

**Comment by xandark** [comment]
Cool! Okay, one issue I've found is that CAT -S -N FILE1 mis-formats. The empty line that would normally be "squeezed" out is numbered, which is okay, but it doesn't have a line feed for the next numbered line. It seems from a test I've done that -N forces all lines to be displayed even if -S is present.

So yes, I think that -B would be mandatory here.

Another issue is that CAT is adding a CR between FILE1 and FILE2, which is probably an artefact of forcing a trailing CR so that the shell's prompt starts on a new line. That insertion behaviour will have to be removed and the burden put onto the shell to check to see if it needs to add a CR when it prints its prompt.

I tested this assumption under Bash and found that all textual files have a terminating CR (actually LF). It's impossible for me to make a text file without one, like using Nano, or by doing a simple "echo 'blah' > /tmp/test". Using a hex-editor, I see that even that "test" file has a terminating CR. 

If I use the hex editor to remove the CR, cat will still add a CR for me in interactive shell mode when there's only one argument to cat. With more than one argument, cat correctly concatenates the two files on screen with no intermediary CR. 

BTW, great to see the new error messages :)

**Comment by xandark** [comment]
To follow up: I noticed that EDIT allows me to make text files that do not have a terminating CR.

**Comment by burniouf** [comment]
fixed "CAT -S -N FILE1 mis-formats"....could you close related "Enhnancements" and open separate "bugs" for remaining issues, please ?
Thanx !

**Comment by xandark** [comment]
Okay, I see that "CAT -S -N FILE1 mis-formats" is corrected, great!

One new thing that is new or I missed is if I do:

$ CD ETC
$ CAT -N HOSTNAME TCPIP.CONF

...the numbering restarts at 1 for TCPIP.CONF instead of continuing at 2. This happens for each consecutive file that is CAT'd. But almost there :)

**Comment by burniouf** [comment]
#384

**Comment by burniouf** [comment]
#384

**Comment by xandark** [comment]
Help me to understand what #384 refers to? I'm not an expert here.

**Comment by burniouf** [comment]
it means that fix is in commit #384

**Comment by xandark** [comment]
I think that this issue can be closed because CAT is now well implemented to replace TYPE.
