### ISSUE TITLE
Floppies are swapped

### ISSUE THREAD

**Issue by SEGStriker** [burniouf/A2osX#30]
Boot floppy is actually dev one and contrariwise...

**Comment by burniouf** [comment]
commit#634

 ok, now A2osX.BOOT contains.......volume "A2osX.BOOT"....and so DEV....
btw, these medias are STILL version 0.9

**Comment by SEGStriker** [comment]
Nevermind, you did great job!
Any plans to develop boot loader independent of ProDOS?

**Comment by burniouf** [comment]
ProDOS FileSystem and API is far enough to host this kernel....and AppleTalk integration is quite trivial within these 2 things...
what you had in mind ?
