### ISSUE TITLE
Another timer source

### ISSUE THREAD

**Issue by EtchedPixels** [burniouf/A2osX#31]
You can abuse any serial card with a transmit interrupt as a timer especially at low baud rates. The tx done/tx buffer empty interrupt just requires re-priming with a byte. As most terminals treat \0 as padding you can (with a small state machine for control codes) even use the port up to about 1200 baud (~120Hz timer) while abusing it as a clock.

**Comment by burniouf** [comment]
Could be an option.

But as far as SSC is used mainly for ADTPro at 11500, or as a serial line for a TTY at 9600, i fear the best solution would be to dedicate the SSC setup at 600 bauds in loopback mode with received IRQ enabled.
sending 10 bits (8+2) could make a 60hz timer....

Would you like me to give it a try with this configuration ?

**Comment by EtchedPixels** [comment]
I'm not sure you need the loopback - the uart will happily transmit into empty air and interrupt when the buffer is done, in fact its more of a pain shutting it up when you don't want to send more 8)

It's not a config I have access too - I mentioned it because I've done a similarly evil trick with a Z80 based SBC that had an RTC but no timer interrupts.

**Comment by patrickbst** [comment]
Given that we now have mouse, thunderclock or NSC and a number of ethernet cards, we probably have enough tic sources at this point.  We did look at Geos card, but they are vary rare and making our own card right now does not make sense.
