### ISSUE TITLE
The root "/" directory doesn't show the volumes that are accessible

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#33]
With 0.9.1 if I do this:

$ PWD
/A2OSX.BOOT/
$ CD ..
$ PWD
/
$ LS

Note that LS doesn't display anything. There's no way to tell how to "get out" of the / directory level.

I was hoping to visually discover that /RAM and /A2OSX.BOOT would be displayed at that root "/" level so that I could intuitively CD into /RAM, but I couldn't. 

I found that I had to blindly CD into /A2OSX.BOOT to get out of that seemingly unmapped space.

**Comment by burniouf** [comment]
Managed to make this happen when one of the 5.25 disk is empty.
Could you confirm ?

**Comment by burniouf** [comment]
Ok, found a stupid bug while enumerating drives....fixed in last build
