### ISSUE TITLE
Bypass the startup file?

### ISSUE THREAD

**Issue by a2retro** [burniouf/A2osX#35]
Hi Rémy, is there a way to bypass the startup file from loading during boot time. I was trying to automate loading the uthernet II driver and tcpipd/dhcp client and I am stuck on a blank screen after i hear all the files being loaded.

**Comment by burniouf** [comment]
HEHEHE!!! good job ;-)
was trapped exactly the same way few days ago.
I suggest making this enhancement high priority!

**Comment by burniouf** [comment]
btw, implementation should be better like "use the last known good startup file", instead...
Or.....step trace and cancel each line....
any suggestion ?

**Comment by burniouf** [comment]
btw, is the cursor blinking ?
no way to switch between screens ?

**Comment by a2retro** [comment]
checking again I think it was just a blank screen

**Comment by burniouf** [comment]
i think simplest way is to setup a hotkey to skip A2osX.startup, and simply start a shell at SYS screen.
when hotkey pressed, execute /SBIN/SHELL instead of /SBIN/SHELL A2OSX.STARTUP
easy tweaks to SYS driver have to be made in order to fully support keyboard input.

**Comment by burniouf** [comment]
Ctrl-D hotkey for "Maintenance Mode" at Init3 has been added to 0.9.2
BOOT media for new kernel 0.9.2 alpha version coming soon....be prepared for intensive debug session!!!! ;-)

**Comment by patrickbst** [comment]
Tested, confirmed feature is working.
