### ISSUE TITLE
Issues with tcpipd

### ISSUE THREAD

**Issue by a2retro** [burniouf/A2osX#37]
1. Your screen shot should be updated to reflect it is now **startproc tcpipd**
2. I create a empty hosts file but tcpipd fails to load it - what should be in this file?
3. tcpip.conf file created but ignores contents - dhcp client works fine to provide ip info

**Comment by burniouf** [comment]
1. i'll update doc/screenshot while reassembling TCPIPD for 0.9.2
2. not yet implemented (static DNS entries impl. is done but not yet parsing "etc/hosts"
3. see https://github.com/burniouf/A2osX/blob/master/ETC/TCPIP.CONF for syntax....

should contains:
IP=192.168.1.150
MASK=255.255.255.0
GW=192.168.1.1
DNS1=192.168.1.2
DNS2=192.168.1.1   (OPTIONAL)
DOMAIN=coincoin.hd.free.fr

**Comment by rgjones33** [comment]
I lost my config - disk II could not be read. Pretty sure I have a faulty 5.25 disk drive

**Comment by burniouf** [comment]
new etc/tcpip.conf file syntax:

```
address 192.168.1.150
netmask 255.255.255.0
gateway 192.168.1.254
nameserver 192.168.1.2
nameserver 192.168.1.254
dnsdomain coincoin.hd.free.fr

```
all 3 ETC files are now parsed during TCPIPD in 0.92, please check, then close this issue.
