### ISSUE TITLE
Consider renaming A2OSX.STARTUP to look more like a shell script

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#4]
Coming into this very cool hybrid Apple II/Unix world, I was looking for things that made sense in both worlds. 

I had to spend more time figuring this out than if its file name were different. It didn't make sense to me that A2OSX.STARTUP was a shell script file based on its name. In the Apple II ProDOS world, a file that has STARTUP in it is usually not a text file, and I wouldn't think to look in it.

If it were called STARTUP.SH or BOOT.SH, then I would've immediately thought, "Okay, I know what that is, it's a shell script. I will start hacking there first!"

My request is to make that file have an extension that reflects that it's a shell script.

**Comment by burniouf** [comment]
Renaming the boot script is trivial, choosing the right name is not.

SBIN/SHELL is not SH, nor BASH....and STARTUP.SHELL is too long, right?

**Comment by xandark** [comment]
Ah, this is more complicated than I thought! From this page [https://unix.stackexchange.com/questions/31760/file-extensions-for-unix-shell-scripts] it's mostly opinion.

I thought the convention is that files that end in .sh are all considered shell scripts. And we could adopt that convention too. For example, sh and bash are different but they both adopt .sh for their scripts by convention.

Maybe it's not necessary to break convention and come up with a new extension name. 

.SHELL is a lot of characters for a ProDOS file name! :) How about STARTUP.SH ? Since there is only one shell in this UNIX implementation, can we just assume that any .SH file will be executed by SHELL?

**Comment by burniouf** [comment]
i suggest :
- adding #!SBIN/SHELL in any scripts files....it will launch the proper interpreter
- prevent execution if #! is NOT present
-  STARTUP.SH is ok 
(plan is to write another interpreter : #!SBIN/XBASIC ;-)

**Comment by xandark** [comment]
I really like the idea of using a #! line and preventing execution if not present! 

Very cool to hear about XBASIC! This environment just keeps getting more and more exciting O_O

**Comment by burniouf** [comment]
XBASIC needs LIBMATH to be written....a task for...later!

**Comment by patrickbst** [comment]
STARTUP has been changed to ETC/INIT and is implemented in the current build.  INIT is going to be continually enhanced to support RUN LEVELS/INIT.d type features in future releases/builds.  There is also consideration being given to supporting Shell Profiles at User login in a future release.  Since STARTUP has now been changed, closing this issue.
