### ISSUE TITLE
Incorrect ram reported with RWIII and a2heaven VGA module

### ISSUE THREAD

**Issue by a2retro** [burniouf/A2osX#41]
![image from ios](https://user-images.githubusercontent.com/13440567/42736639-06fc00c6-8837-11e8-9f67-03b5ecf66e8f.jpg)

My RWIII card only has 16 - 41256 chips on it. /RAM4 is from my slinky card. Not sure about /RAM2

**Comment by burniouf** [comment]
Could you confirm which RWIII banks are populated ?

**Comment by a2retro** [comment]
The top 2 banks

**Comment by burniouf** [comment]
mmmm .... i suspect :
/RAM2 is your RAMWORKS
/RAM3 is your FatChip //e

Could you make some tests removing boards one at a time to confirm this ?

**Comment by a2retro** [comment]
So with only RWIII /RAM3 report 896 blocks (5 used)
With FastChip //e and RWIII it is the same for /RAM3 and /RAM2 as the screen above
/RAM4 is the slinky card

**Comment by burniouf** [comment]
after a quick reading of Fastchip //e manual, seems this board emulate a RAMWORKS III
the 2 boards may conflict, i fear.
try disabling Fastchip //e RAMWORKS, to be sure...

`N.B If you have an actual RamWorks board in your system and enable the emulation
on the FASTChip //e board it will clash with the actual RamWorks board, effectively
disabling it. Hence you should not enable the RamWorks emulation n the FASTChip
//e if you have a physical RamWorks board installed in your system.`

as written in the manual.

**Comment by rgjones33** [comment]
Oops, I guess I better read the manual next time. I didn't check the FastChip config. Will have a look .

**Comment by patrickbst** [comment]
Glenn, can you confirm and close this issue?  Thanks.

**Comment by patrickbst** [comment]
@a2retro Glenn, since I have not heard back, going to go ahead close.  Feel free to reopen if this was in error.
