### ISSUE TITLE
DHGR routine

### ISSUE THREAD

**Issue by sup4rl33thax0r** [burniouf/A2osX#43]
Thought you might want to look at my DHGR routine for loading BMP files, it's pretty optimized and might help at some point along the way?

Also, take note of my build environment.  I'm using VS Code which allows everything to build and run under Virtual ][ (I understand you're on Windows and this is on a Mac but the build scripts can be modified to work with AppleWin, on my to-do list actually).  Scripting builds this way is super useful and really reduces iteration time.  I don't know how many hours I saved myself with this setup, beforehand it was almost intolerable!

Anyway, you can check out my GitHub here:  https://github.com/sup4rl33thax0r/keplermatik-map

The larger project for this is:  https://hackaday.io/project/5358-keplermatik

**Comment by patrickbst** [comment]
Added project to watch list for continue review in the future.  Thanks for making us aware of this great project.
