### ISSUE TITLE
Document how to build project

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#45]
This is such a *amazing* project but it took me a long, long time to infer that A2osX is host-assembled, not cross-assembled. 

This is unusual in today's retro-scene, but this fact needs to be pointed out right up front so that others can clearly understand what you're doing, and how to follow along. 

In the Readme.md file, it is mentioned which editor is used for the primary development, but it doesn't mention anywhere that the cross-edited source files are pushed into a boot disk image, and that image is booted into an emulator, where the custom make file runs a self-provided assembler to assemble the code. It's effective for you, but it's unusual for us, and I think this workflow is daunting the already limited supply of potential Apple II developers out there. At least it did for me for months. It's also strange because this is a Unix-on-a-//e project but the development process isn't Unix-y. It's counter-intuitive.

In the "Notes for Developers.md" file, it talks about editors, but it would be much more helpful if the assembler was described, where it's located, the full build process was shown, and your rationale for choosing your process over a cross-assembling strategy. That way we can at least try to understand why we should adapt to this model.

The make scripts that I examined didn't make much sense to me because they don't follow the typical GNU make convention that I am used to seeing. And I didn't understand how they fit into the build process.

Issue #43 mentions a cross-development workflow that he wants to contribute, and there are other Apple II solutions out there that use standard POSIX dev tools.

I think that if this project had more documentation on the build process, it would help a lot.

**Comment by patrickbst** [comment]
Hi Xandark.

First, let me apologize, I pushed to GitHub a document I was in the process of creating, way early in its life cycle, which I think only added to your confusion.  Of course I am talking about Notes for Developers, where I was curating the very information I think you were seeking, i.e. how to write apps in/for A2osX. I will push an update to this document tonight or tomorrow which hopefully answers all your questions or at least provide a good base for discussing the A2osX development process.

As a side note, you mention that #43 discuses another cross-dev workflow and you asked/for seek other solutions. When I first joined this project, I started pestering Remy (the Architect behind A2osX) about using CC65/ASM65 or Merlin or TurboPlusExtraPowerAsmX and realized later was what I first needed to understand was why this platform and where the project was headed.  I am trying to capture what I learned in the Notes to Dev doc.

**Comment by patrickbst** [comment]
Xandark,

I just pushed an update to the Developers document.  It is still not complete, I will finish tomorrow.  It answers some of your questions (how we do things now).  But the why S-C assembler and next dev phase need to be done which I think will answer the rest of the questions you posed.  Feel free to comment on anything in this draft so we can make the final version a better product for all devs.  Thanks again for your interest and support of this project.

Patrick

**Comment by xandark** [comment]
Hello Patrick, yes much improved and it brings to light how to build A2osX, well done!

**Comment by patrickbst** [comment]
Xandark, thanks for the response.  I am continuing to update this document and hope to have another refresh available later tonight.  I want to ask.  What is your experience with ASM.  Can we suggest a small project to get you started with A2osX that will help you get more familiar with developing and hopefully benefit the larger community.

Patrick

**Comment by xandark** [comment]
Hello Patrick, my experience with ASM is rusty, but that's not my issue. My issue are my other commitments in my life right now, and so I can only peek in from time to time and see how the project is progressing. It's one of the few A2 projects that I follow.

**Comment by patrickbst** [comment]
Thanks for the response.  Would love to see you on the A2osX team when you have the time.  We are continuing to add to the doc to make it better for devs like you.  In addition, Remy has been working non-stop lately to get the internal ASM working so that you will be able to self-build right in A2osX.  Be sure to keep up with updates to README/NEWS/and Docs!

I am going to close this issue since I think we addresses the original question with our **[Developers Guide](.Docs/Developers%20Guide.md)**.
