### ISSUE TITLE
Access to /DEV/CONSOLE

### ISSUE THREAD

**Issue by patrickbst** [burniouf/A2osX#46]
It seems that if you try to send something to /DEV/CONSOLE for example with **ECHO Hello > /DEV/CONSOLE** you get a File Already Open Error.  As we add more Server Processes to A2osX like HTTPD and TELNETD that are not associated with a user, but with the system, they should have a way of writing to the CONSOLE.  Perhaps when you NOHUP a process it should automatically copy STDOUT/STDERR from PS0.

**Comment by burniouf** [comment]
It does.
NOHUPing a process makes it run under PS0 which has stdin/stdout/stderr = /dev/console

to close.

**Comment by patrickbst** [comment]
Does this mean that if I wanted to write a message to /dev/console from a "user session" i could do this by creating a script that just ECHO $1 and then do **NOHUP script MyMessage** ?

**Comment by patrickbst** [comment]
I made a script to test this and NOHUP always gives a file not found error.    I finally tried NOHUP SH and guess what, you now have shell running on console.  wheeeee.  root user hack!

**Comment by patrickbst** [comment]
Closing issue.
