### ISSUE TITLE
Can TYPE detect absence of final CR in files and add one if not present?

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#6]
I notice that your text files, like L and HOSTNAME, don't have an ending carriage return in them which makes TYPE'ing them print a shell $ on the same line as the file content. Like this:

```
$ TYPE BIN/L
LS -L $2 $3 $4 $4 $ (now input  is here)
```

Is there a way that TYPE could detect that case and add a CR so that the input prompt doesn't look messy and the user needing to type a CR? This is a small detail, but I was thinking either that or I would go in and add CR's to all the text files :)

**Comment by burniouf** [comment]
actually correcting BUG #5 
this enh is already added.  ;-)

**Comment by burniouf** [comment]
#348 : included in BUGFIX#5

**Comment by xandark** [comment]
Thinking about this issue some more while trying to fall asleep :) I realized that tweaking TYPE to guard against not having a terminating CR is the brittle approach. Because there will always be some corner case that will have to be checked against to ensure that the output has a terminating CR, and that's just too much work.

It seems to me that the more robust solution would be to shift the responsibility to SHELL; when it wants to print a $ prompt, it checks to see if it's on column 1, and if not, it inserts a CR to get there. That way the prompt is always clear and visible.

**Comment by burniouf** [comment]
For now, the "trick" to examine last char is doing the job, i suggest leaving it like this and going ahead to more critical features.

**Comment by xandark** [comment]
Okay, understandable, it's still good. I'll mark this as done.
