### ISSUE TITLE
GETKEY special keys

### ISSUE THREAD

**Issue by patrickbst** [burniouf/A2osX#60]
One issue on your GETKEY, you dont seem to allow for the one char buffer that is   standard on Apple. You have to keep   mashing the key you want before it is accepted.  It seems that in that while loop, you have to hit the key at the moment script is processing that getkey line.  So if I press a key and it is doing other   stuff in loop, it ignores my keypress.

From XLS 192

**Comment by patrickbst** [comment]
From RG:  Fixed a bug in kernel not returning the proper keycode.  No way to buffer KBD state, //e does not generate IRQ for keyboard.  We must implement READ -N 1 to do what you want

**Comment by burniouf** [comment]
done in .93
