### ISSUE TITLE
Add -A switch to LS to disable appearance of ./ and ../

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#7]
When issuing a LS -R, I'm seeing a lot of ./ and ../ the output, which is more distracting than helpful, especially in a recursive listing where I know that a directory has a parent, because it's nature is hierarchical. In this context, I really want to see the files, not the meta-files.

Thinking about it more, it would be nice to have a LS switch that disables the ./ and ../ entries. These are the arguments I'm seeing for my GNU LS command on this matter:

       -A, --almost-all
              do not list implied . and ..

By the way, the GNU LS -a is different from -A, and does "not ignore entries starting with ."

And if -R is used, then I could at least do an -R -A.

**Comment by burniouf** [comment]
#349 : LS -A switch (and a lot of bugfixes)

**Comment by xandark** [comment]
Excellent, works great!
