### ISSUE TITLE
CUT Command

### ISSUE THREAD

**Issue by patrickbst** [burniouf/A2osX#76]
We need  a cut command which could be used to pull fields of data out of output or   files (CUT file types out of L listings, or CUT user ID from passwd file). -d  option to delimit by char (:). -f pulls fields by that delimiter.
--From S0010

**Comment by patrickbst** [comment]
CUT command has been added by development.  Needs documentation, test script and example for user guide.

**Comment by patrickbst** [comment]
CUT only works on one line of input.  Typically a cut command, works on multiple lines of input, cutting the same columns, fields or bytes from each.  A2osX CUT should follow this same pattern.

**Comment by xandark** [comment]
I will file a bug for this, as I was expecting the normal CUT conventions.

**Comment by patrickbst** [comment]
Xandark, I was wrong, I was actually just responding to what CUT did at the time, not what it should have.  This has since been correct and doc has been updated. Closing this (as this item is closed, there is a separate new open issue on open CUT bug related to piping).
