### ISSUE TITLE
TYPE command doesn't pause with Ctrl-S nor die with Ctrl-C

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#8]
$ TYPE A2OSX.STARTUP
(starts to list)
(Ctrl-S won't pause it)
(continues to list)
(Ctrl-C won't kill it)

**Comment by burniouf** [comment]
Well, let's impement a CAT external command and remove TYPE from shell internals...

linked to #3

**Comment by xandark** [comment]
TYPE is now CAT, and this works now :+1:
