### ISSUE TITLE
AppleTalk programmers documentation needed

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#9]
Don't know how to send you a personal message and I noticed that you're looking for AppleTalk Programmer's documentation. I don't have it and I'm sure you've found these tech notes?

https://archive.org/details/AppleTalk_Technical_Notes

**Comment by burniouf** [comment]
Now you should be able to send me personal emails.
got this doc already, but thanx for the efforts ;-)

**Comment by xandark** [comment]
If you could help with issue #13 then it would be easier for me to help promote this project and get the documentation.

**Comment by snhirsch** [comment]
Are you looking for Inside Appletalk or the Apple 2 Appletalk Programmers manual?

**Comment by burniouf** [comment]
best would be "appletalk programmer's guide for the apple II", but any reference book dealing with AppleTalk API could fit.
Thanx for your help

**Comment by snhirsch** [comment]
Please drop me private e-mail (snhirsch at <ignore this> gmail.com) with your private e-mail and I'll arrange to get it to you.

**Comment by burniouf** [comment]
Done.

**Comment by burniouf** [comment]
PERFECT!!! exactly what i need. Thanx a LOT!
