### ISSUE TITLE
ECHO enhancement

### ISSUE THREAD

**Issue by patrickbst** [burniouf/A2osX#99]
Can we add the \a or bell special char so we can ECHO "\a" a bell per the VT-100 standard?  Is this a big thing (lot of code or a simple apple call)?
--From S0063

**Comment by burniouf** [comment]
\a added to printf (and ECHO)

...but NOT to terminal.

**Comment by patrickbst** [comment]
What do you mean by not to terminal?

**Comment by patrickbst** [comment]
FYI, tested ECHO \a in latest build on AW in both console and putty as well as on real //e.  No beep.  Santas elf sad.

**Comment by burniouf** [comment]
ECHO \a makes PuTTY emit a bell (windows system sound, check if not disabled)
A2osX VT100 will not emit a beep...to do so IRQ must be disabled for a long period to emit not distorted sound.....which is not a good idea under A2osX....
you have to wait for someone writing a Mockingboard driver that could play "TADA!!!" and all that sort of things....

**Comment by KrisKennaway** [comment]
Another option would be a "visual bell" - flash a status line on the
screen, or somesuch.

**Comment by burniouf** [comment]
Good Idea....let's put that on .94

**Comment by patrickbst** [comment]
Confirmed, bell works in putty.  Closing this issue. Note, putty does allow you to set whether it rings bell, plays system sound or do a flash of the window.  For console connected sessions or when you are using TERM or TELNET from HW to other systems a flash of the screen or inverse BELL in the middle of the screen or something might be nice.  On the GS, can you produce a sound with a simple call or do you have to do the same ASM loop that ticks the speaker interrupt or what have you to produce sound?  Is someone up to writing a routine that plays a sound through a mockingboard?
